# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:cosody/animations/flight.animation/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.flight.animation.frame 1