# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cosody.root] run return 0
execute on passengers if entity @s[tag=aj.cosody.data] unless data entity @s {data:{rigHash: '1d79b3ea818e76b83fee0fab551f999b68238653f92bdf146c64096a1785143a'}} on vehicle run function animated_java:cosody/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1