# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cosody.root] run return 0
execute on passengers if entity @s[tag=aj.cosody.data] unless data entity @s {data:{rigHash: 'b35be3ca76d68f2d188884def2b17e8559be7e214a3843c01c6f88939b2a5121'}} on vehicle run function animated_java:cosody/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1