# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.cosody.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cosody', 'function_path': 'animated_java:cosody/variants/console/apply'}
execute on passengers if entity @s[tag=aj.cosody.bone.console_base] run function animated_java:cosody/variants/console/zzz/0
execute on passengers if entity @s[tag=aj.cosody.bone.rotor_colom] run function animated_java:cosody/variants/console/zzz/1
execute on passengers if entity @s[tag=aj.cosody.bone.hexadecagon] run function animated_java:cosody/variants/console/zzz/2
execute on passengers if entity @s[tag=aj.cosody.bone.octagon] run function animated_java:cosody/variants/console/zzz/3
execute on passengers if entity @s[tag=aj.cosody.bone.octagon2] run function animated_java:cosody/variants/console/zzz/4